name: "\U0001F41E Bug report"
description: Create a report to help us improve Bool Bridge
labels: ["pending triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this bug report!
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is. Thanks!
      placeholder: Bug description
    validations:
      required: true
  - type: checkboxes
    id: service
    attributes:
      label: Affected service
      description:  Which service are you experiencing the problem with?
      options:
        - label: Bool Bridge
        - label: B² Bridge
        - label: CKB Bridge
    validations:
      required: true
  - type: checkboxes
    id: required-info
    attributes:
      label: Final checks
      description: Before submitting, please make sure you do the following
      options:
        - label: Check existing [issues](https://github.com/boolnetwork/bool-bridge-feedback/issues).
          required: true