name: "🌟 Chain Support Request"
description: Request a new chain to be supported in our bridge
labels: ["pending triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this chain support request!
  - type: input
    id: chain-name
    attributes:
      label: Chain Name
      placeholder: e.g., zkSync
    validations:
      required: true
  - type: input
    id: chainid
    attributes:
      label: Chain ID
      description: Provide the Chain ID if it's an EVM chain.
      placeholder: e.g., 1 for Ethereum, 56 for BSC
  - type: input
    id: chain-rpcs
    attributes:
      label: Chain RPCs
      description: If available, provide RPC endpoints for the chain.
      placeholder: Chain RPCs
    validations:
      required: true
  - type: input
    id: chain-explorer
    attributes:
      label: Chain Explorer
      description: If available, provide explorer for the chain.
      placeholder: Chain explorer
    validations:
      required: true
  - type: checkboxes
    id: chain-type
    attributes:
      label: Chain Type
      description: Select the type of chain.
      options:
        - label: BTC Layer2
        - label: ETH Layer2
        - label: EVM 
        - label: Non-EVM chain
        - label: Other
    validations:
      required: true
  - type: textarea
    id: reason
    attributes:
      label: Reason for Request
      description: Please explain why this chain should be supported.
      placeholder: Enter your reasoning here
  - type: checkboxes
    id: required-info
    attributes:
      label: Final Checks
      description: Before submitting, please ensure you have done the following
      options:
        - label: I have checked existing [issues](https://github.com/boolnetwork/bool-bridge-feedback/issues) for similar requests.
          required: true