name: "🚀 Token Support Request"
description: Request a new token to be supported in our bridge
labels: ["pending triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this token support request!
  - type: input
    id: token-name
    attributes:
      label: Token Name
      description: Full name of the token
      placeholder: e.g., Ethereum, Bitcoin
    validations:
      required: true
  - type: input
    id: token-symbol
    attributes:
      label: Token Symbol
      description: Trading symbol of the token
      placeholder: e.g., ETH, BTC
    validations:
      required: true
  - type: input
    id: token-decimal
    attributes:
      label: Token Decimals
      description: Number of decimal places for the token
      placeholder: e.g., 18 for ETH, 8 for BTC
    validations:
      required: true
  - type: input
    id: token-link
    attributes:
      label: Token Link
      description: For ERC20 tokens, provide the token's explorer URL. For BRC20 or Runes, provide a Unisat link.
      placeholder: e.g., https://etherscan.io/address/0x...
    validations:
      required: true
  - type: dropdown
    id: token-type
    attributes:
      label: Token Type
      description: Select the type of token
      options:
        - BRC-20
        - RUNES
        - ERC-20
        - xUDT
        - Other
    validations:
      required: true
  - type: checkboxes
    id: service
    attributes:
      label: Requested Services
      description: Which services should support this token?
      options:
        - label: Bool Bridge
        - label: B² Bridge
        - label: CKB Bridge
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Additional Details
      description: Provide more information, including which chains you want to bridge the assets between, etc.
      placeholder: Enter additional details here
  - type: checkboxes
    id: required-info
    attributes:
      label: Final Checks
      description: Before submitting, please ensure you have done the following
      options:
        - label: I have checked existing [issues](https://github.com/boolnetwork/bool-bridge-feedback/issues) for similar requests.
          required: true